database:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: example
  properties: # https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby
    maximumPoolSize: 10